begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
create function pg_temp.login(i integer) returns void language plpgsql as $$
begin
 perform set_config('role','authenticated',true);
 perform set_config('request.jwt.claims',json_build_object('sub','30000000-0000-0000-0000-'||lpad(i::text,12,'0'),'role','authenticated')::text,true);
end $$;
create function pg_temp.wc(sql text) returns integer language plpgsql as $$
declare n integer; begin execute sql; get diagnostics n=row_count; return n; end $$;
insert into auth.users(instance_id,id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,email_change,email_change_token_new,recovery_token)
select '00000000-0000-0000-0000-000000000000',('30000000-0000-0000-0000-'||lpad(i::text,12,'0'))::uuid,'authenticated','authenticated','beta-ux-'||i||'@example.test','{}','{}',now(),now(),'','','','' from generate_series(1,5) i;
select pg_temp.login(1);
select throws_ok($$select public.create_project('No date','UTC','GBP')$$,'22023',null,'Start required at RPC boundary');
create temporary table ctx as select public.create_project('Beta UX Test','UTC','GBP',current_date,null,'blank') as id;
select ok((select ends_on is null from public.projects where id=(select id from ctx)),'End date remains optional');
set local role postgres;
insert into public.project_members(project_id,user_id,display_name,role,status)
select ctx.id,('30000000-0000-0000-0000-'||lpad(i::text,12,'0'))::uuid,'Collaborator '||i,case when i=2 then 'member' else 'viewer' end::public.member_role,'active' from ctx cross join generate_series(2,4) i;
-- A legacy null start remains editable; no global NOT NULL constraint/backfill.
update public.projects set starts_on=null where id=(select id from ctx);
select pg_temp.login(1);
select lives_ok($$update public.projects set name='Beta UX Test' where id=(select id from ctx)$$,'Legacy null-date project editable');
create temporary table act as select (public.save_activity_with_split((select id from ctx),null,'{"title":"Book restaurant","kind":"other","activity_type":"other","estimated_cost_minor":10000}',null)).id;
select ok((select owner_member_id is null and location_label is null from public.commitments where id=(select id from act)),'Activity needs no owner or location');
update public.commitments set status='researching' where id=(select id from act);
select is((select count(*)::int from public.get_project_health((select id from ctx)) where code='missing_owner'),0,'No missing-owner Health noise');
select is((select total_cost_minor from public.v_project_financials where project_id=(select id from ctx)),10000::bigint,'Activity cost counted');
create temporary table paid as select gen_random_uuid() id;
select lives_ok($$insert into public.payments(id,project_id,commitment_id,type,direction,amount_minor,status,paid_on) select paid.id,ctx.id,act.id,'deposit','outgoing',3000,'paid',current_date from ctx,act,paid$$,'One-step deposit paid insert');
select is((select outstanding_minor from public.v_commitment_financials where commitment_id=(select id from act)),7000::bigint,'Deposit leaves 70');
select throws_ok($$update public.commitments set status='completed' where id=(select id from act)$$,'P0001',null,'Completion still gated');
select throws_ok($$update public.payments set amount_minor=1 where id=(select id from paid)$$,'P0001',null,'Paid amount frozen');
select lives_ok($$insert into public.payments(project_id,commitment_id,type,direction,amount_minor,status,paid_on) select ctx.id,act.id,'balance','outgoing',7000,'paid',current_date from ctx,act$$,'One-step balance paid insert');
select lives_ok($$update public.commitments set status='completed' where id=(select id from act)$$,'Settled activity completes');
select lives_ok($$insert into public.payments(project_id,commitment_id,type,direction,amount_minor,status,paid_on) select ctx.id,act.id,'refund','incoming',1000,'paid',current_date from ctx,act$$,'Refund supported after completion');
select is((select net_paid_minor from public.v_commitment_financials where commitment_id=(select id from act)),9000::bigint,'Refund reduces net paid');
create temporary table independent as select * from public.create_task_with_cost((select id from ctx),'{"title":"Independent task","item_type":"booking"}',2500);
select is((select item_type from independent),'booking','Item type is persisted');
select is((select total_cost_minor from public.v_project_financials where project_id=(select id from ctx)),12500::bigint,'Independent task counted once in existing ledger');
create temporary table linked as select * from public.create_task_with_cost((select id from ctx),jsonb_build_object('title','Book transfer','commitment_id',(select id from act)),10000);
select is((select total_cost_minor from public.v_project_financials where project_id=(select id from ctx)),12500::bigint,'Linked task does not duplicate activity cost');
select throws_ok($$select public.create_task_with_cost((select id from ctx),jsonb_build_object('title','Conflicting cost','commitment_id',(select id from act)),9000)$$,'P0001',null,'Conflicting linked costs rejected');
create temporary table zero_task as select * from public.create_task_with_cost((select id from ctx),'{"title":"Zero task"}',0);
create temporary table free_task as select * from public.create_task_with_cost((select id from ctx),'{"title":"No cost task"}',null);
select ok((select commitment_id is null from free_task),'Null cost stays no financial record');
select is((select estimated_cost_minor from public.commitments where id=(select commitment_id from zero_task)),0::bigint,'Explicit zero stays zero');
select throws_ok($$select public.create_task_with_cost((select id from ctx),'{"title":"Invalid"}',0.5)$$,'22023',null,'No fractional minor units');
update public.tasks set assignee_member_id=(select id from public.project_members where project_id=(select id from ctx) and user_id='30000000-0000-0000-0000-000000000003') where id=(select id from independent);
create temporary table repeating as select * from public.create_task_with_cost((select id from ctx),jsonb_build_object('title','Weekly assigned Task','assignee_member_id',(select assignee_member_id from public.tasks where id=(select id from independent)),'recurrence_frequency','weekly','recurrence_interval',1,'recurrence_start_date',current_date),null);
select pg_temp.login(3);
select lives_ok($$select public.complete_assigned_task((select id from repeating),current_date)$$,'Viewer can complete own recurring occurrence');
select throws_ok($$select public.complete_assigned_task((select id from repeating),current_date)$$,'P0001',null,'Viewer cannot rewrite completed occurrence');
select throws_ok($$select public.complete_assigned_task((select id from repeating),current_date+1)$$,'P0001',null,'Viewer cannot invent occurrence date');
select is(pg_temp.wc($$update public.task_occurrences set status='skipped',completed_at=null,skipped_at=now() where task_id=(select id from repeating)$$),0,'Viewer cannot skip or edit occurrences directly');
select lives_ok($$select public.complete_assigned_task((select id from independent))$$,'Assigned Viewer completes own Task');
select is((select status::text from public.tasks where id=(select id from independent)),'done','Done persisted');
select is(pg_temp.wc($$update public.tasks set status='open' where id=(select id from independent)$$),0,'Viewer cannot reopen completed task');
select is(pg_temp.wc($$update public.projects set name='Forbidden' where id=(select id from ctx)$$),0,'Viewer cannot edit project');
select throws_ok($$insert into public.payments(project_id,commitment_id,type,direction,amount_minor,status,paid_on) select ctx.id,act.id,'full','outgoing',100,'paid',current_date from ctx,act$$,'42501',null,'Viewer cannot record arbitrary payments');
select throws_ok($$select public.complete_assigned_task((select id from linked))$$,'42501',null,'Unassigned Viewer denied');
select is(pg_temp.wc($$update public.tasks set title='Hacked',due_on=current_date,assignee_member_id=null where id=(select id from independent)$$),0,'Viewer cannot edit any Task fields');
select is(pg_temp.wc($$update public.commitments set estimated_cost_minor=1 where id=(select commitment_id from independent)$$),0,'Viewer cannot edit task cost ledger');
select throws_ok($$select public.create_task_with_cost((select id from ctx),'{"title":"Forbidden"}',10)$$,'42501',null,'Viewer cannot create task costs');
select pg_temp.login(4);
select throws_ok($$select public.complete_assigned_task((select id from independent))$$,'42501',null,'Viewer cannot complete another collaborator task');
select pg_temp.login(1);
update public.tasks set status='open' where id=(select id from independent);
set local role postgres;
update public.project_members set status='removed',removed_at=now() where project_id=(select id from ctx) and user_id='30000000-0000-0000-0000-000000000003';
select pg_temp.login(3);
select throws_ok($$select public.complete_assigned_task((select id from independent))$$,'42501',null,'Removed Viewer denied');
select pg_temp.login(1);
update public.tasks set assignee_member_id=(select id from public.project_members where project_id=(select id from ctx) and user_id='30000000-0000-0000-0000-000000000004') where id=(select id from independent);
select pg_temp.login(2);
select lives_ok($$update public.tasks set title='Member edit' where id=(select id from linked)$$,'Member permissions retained');
select pg_temp.login(1);
-- Historical estimates remain intact through ordinary effective-cost editing.
select public.set_commitment_actual_cost((select id from act),9500,false);
select lives_ok($$select public.save_activity_with_split((select id from ctx),(select id from act),'{"actual_cost_minor":9000}',null)$$,'Normal editing supports historical actual');
select is((select estimated_cost_minor from public.commitments where id=(select id from act)),10000::bigint,'Historical estimate retained');
select lives_ok($$update public.payments set status='paid',paid_on=current_date where id=(select id from paid)$$,'Reopened payment can be marked paid again');
select lives_ok($$select public.soft_delete_commitment((select id from act))$$,'Activity soft deletion confirmed');
select is((select count(*)::int from public.commitments where id=(select id from act)),0,'Normal member cannot read deleted Activity');
select is((select count(*)::int from public.v_commitment_financials where commitment_id=(select id from act)),0,'Deleted excluded from normal financial view');
select is((select count(*)::int from public.tasks where id=(select id from linked)),0,'Linked task soft-deleted by existing cascade');
set local role postgres;
select ok((select deleted_at is not null from public.commitments where id=(select id from act)),'Historical Activity retained');
select is((select count(*)::int from public.payments where commitment_id=(select id from act) and status='paid'),3,'Paid/refund history retained');
select set_config('request.jwt.claims','{}',true);
update public.users set platform_role='admin' where id='30000000-0000-0000-0000-000000000001';
select pg_temp.login(1);
select is((select count(*)::int from public.commitments where id=(select id from act)),1,'Admin historical access intentionally retained');
select is((select count(*)::int from public.commitments where id=(select id from act) and deleted_at is null),0,'Explicit normal-list filter excludes admin historical rows');
select lives_ok($$update public.payments set status='scheduled',paid_on=null where id=(select id from paid)$$,'Existing paid reopen mechanism retained');
select lives_ok($$update public.payments set ever_paid=false where id=(select id from paid)$$,'Attempt to clear history flag does not fail harmlessly');
select ok((select ever_paid from public.payments where id=(select id from paid)),'Ever-paid history latch cannot be cleared');
update public.projects set status='archived' where id=(select id from ctx);
select throws_ok($$select public.create_task_with_cost((select id from ctx),'{"title":"Archived"}',10)$$,'42501',null,'Archived cost creation denied');
select pg_temp.login(4);
select throws_ok($$select public.complete_assigned_task((select id from independent))$$,'42501',null,'Assigned Viewer denied in archived project');
select pg_temp.login(5);
select is((select count(*)::int from public.tasks where project_id=(select id from ctx)),0,'Nonmember read remains denied');
select throws_ok($$select public.complete_assigned_task((select id from independent))$$,'42501',null,'Nonmember completion denied');
select * from finish();
rollback;
