begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
create function pg_temp.login(i integer) returns void language plpgsql as $$
begin
 perform set_config('role','authenticated',true);
 perform set_config('request.jwt.claims',json_build_object('sub','31000000-0000-0000-0000-'||lpad(i::text,12,'0'),'role','authenticated')::text,true);
end $$;
create function pg_temp.wc(sql text) returns integer language plpgsql as $$
declare n integer; begin execute sql; get diagnostics n=row_count; return n; end $$;
insert into auth.users(instance_id,id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,email_change,email_change_token_new,recovery_token)
select '00000000-0000-0000-0000-000000000000',('31000000-0000-0000-0000-'||lpad(i::text,12,'0'))::uuid,'authenticated','authenticated','ia-'||i||'@example.test','{}','{}',now(),now(),'','','','' from generate_series(1,5) i;
select pg_temp.login(1);
select throws_ok($$select public.create_project('No date','UTC','GBP')$$,'22023',null,'Start required at RPC boundary');
create temporary table ctx as select public.create_project('Ibiza 2027','UTC','GBP',current_date,null,'blank') as id;
select ok((select ends_on is null from public.projects where id=(select id from ctx)),'End date remains optional');
set local role postgres;
insert into public.project_members(project_id,user_id,display_name,role,status)
select ctx.id,('31000000-0000-0000-0000-'||lpad(i::text,12,'0'))::uuid,'Collaborator '||i,case when i=2 then 'member' else 'viewer' end::public.member_role,'active' from ctx cross join generate_series(2,4) i;
select pg_temp.login(1);
create temporary table area(id uuid);
with a as(insert into public.project_areas(project_id,title) select id,'Transport' from ctx returning id) insert into area select id from a;
select throws_ok($$select public.create_activity_in_category((select id from ctx),null,'{"title":"No category"}',null)$$,'22023',null,'New Activity requires a Category');
create temporary table empty_area as with a as(insert into public.project_areas(project_id,title) select id,'Unused' from ctx returning id) select id from a;
select lives_ok($$select public.delete_project_category((select id from empty_area))$$,'Empty Category can be deleted');
create temporary table item as select (public.save_activity_with_split((select id from ctx),null,jsonb_build_object('title','Taxi','activity_type','booking','area_id',(select id from area),'estimated_cost_minor',10000),null)).id;
select is((select area_id from public.commitments where id=(select id from item)),(select id from area),'Item belongs to Area');
select is((select cost_minor from public.v_area_totals where area_id=(select id from area)),10000::bigint,'Area cost once');
select throws_ok($$select public.delete_project_category((select id from area))$$,'P0001',null,'Category with Activities cannot be deleted');
select is((select net_actual_spend_minor from public.v_project_financials where project_id=(select id from ctx)),0::bigint,'Unpaid cost is not spent');
select public.set_activity_cost_split((select id from item),jsonb_build_object('mode','even','cost',10000,'members',(select jsonb_agg(id order by id) from public.project_members where project_id=(select id from ctx) and role in ('organizer','member'))));
insert into public.payments(project_id,commitment_id,type,amount_minor,status,paid_on,paid_by_member_id) select ctx.id,item.id,'full',10000,'paid',current_date,m.id from ctx,item,public.project_members m where m.project_id=ctx.id and m.role='organizer';
select is((select net_actual_spend_minor from public.v_project_financials where project_id=(select id from ctx)),10000::bigint,'Taxi expense 100');
select is((select remaining_minor from public.v_activity_member_settlements where commitment_id=(select id from item) and member_status='active' and display_name='Collaborator 2'),5000::bigint,'Michael owes 50');
create temporary table settlement as select public.record_item_settlement((select id from item),(select id from public.project_members where project_id=(select id from ctx) and role='member'),(select id from public.project_members where project_id=(select id from ctx) and role='organizer'),5000,current_date) id;
set constraints all immediate;
select is((select net_actual_spend_minor from public.v_project_financials where project_id=(select id from ctx)),10000::bigint,'Settlement never reduces expense');
select is((select gross_paid_minor from public.v_project_financials where project_id=(select id from ctx)),10000::bigint,'Settlement not gross supplier spend');
select is((select refunded_minor from public.v_project_financials where project_id=(select id from ctx)),0::bigint,'Settlement not supplier refund');
select is((select remaining_minor from public.v_activity_member_settlements where commitment_id=(select id from item) and display_name='Collaborator 2'),0::bigint,'Michael settled');
select is((select spent_minor from public.v_area_totals where area_id=(select id from area)),10000::bigint,'Area spent still 100');
set constraints all deferred;
select lives_ok($$select public.cancel_item_settlement((select id from settlement))$$,'Atomic settlement correction');
set constraints all immediate;
select is((select remaining_minor from public.v_activity_member_settlements where commitment_id=(select id from item) and display_name='Collaborator 2'),5000::bigint,'Cancellation restores debt');
select is((select net_actual_spend_minor from public.v_project_financials where project_id=(select id from ctx)),10000::bigint,'Correction preserves expense');
create temporary table beta as select * from public.create_task_with_cost((select id from ctx),'{"title":"Atomic beta cost"}',2500);
select is((select count(*)::int from public.v_project_items where title='Atomic beta cost'),1,'Synthetic ledger appears as one Item');
select is((select sum(cost_minor)::bigint from public.v_project_items where project_id=(select id from ctx)),12500::bigint,'Projection counts financial costs once');
create temporary table linked as select * from public.create_task_with_cost((select id from ctx),jsonb_build_object('title','Related work','commitment_id',(select id from item)),10000);
select is((select sum(cost_minor)::bigint from public.v_project_items where project_id=(select id from ctx)),12500::bigint,'Linked work never repeats expense');
create temporary table own as select (public.save_activity_with_split((select id from ctx),null,jsonb_build_object('title','Sarah task','activity_type','task','owner_member_id',(select id from public.project_members where project_id=(select id from ctx) and user_id='31000000-0000-0000-0000-000000000003')),null)).id;
select pg_temp.login(3);
select lives_ok($$select public.complete_assigned_item((select id from own))$$,'Viewer completes own Item');
select is(pg_temp.wc($$update public.commitments set title='Forbidden',estimated_cost_minor=1,area_id=null where id=(select id from own)$$),0,'Viewer cannot edit fields');
select throws_ok($$select public.complete_assigned_item((select id from item))$$,'42501',null,'Viewer cannot complete other Item');
select throws_ok($$insert into public.project_areas(project_id,title) select id,'Forbidden' from ctx$$,'42501',null,'Viewer cannot create Area');
select throws_ok($$select public.record_item_settlement((select id from item),null,null,1,current_date)$$,'42501',null,'Viewer cannot settle');
select pg_temp.login(5);
select is((select count(*)::int from public.project_areas where project_id=(select id from ctx)),0,'Nonmember cannot see Areas');
select is((select count(*)::int from public.v_project_items where project_id=(select id from ctx)),0,'Nonmember cannot see Items');
select pg_temp.login(1);
select pg_temp.login(1);
set constraints all deferred;
select lives_ok($$select public.record_item_settlement((select id from item),(select id from public.project_members where project_id=(select id from ctx) and role='member'),(select id from public.project_members where project_id=(select id from ctx) and role='organizer'),2000,current_date)$$,'Partial settlement supported');
set constraints all immediate;
select is((select remaining_minor from public.v_activity_member_settlements where commitment_id=(select id from item) and display_name='Collaborator 2'),3000::bigint,'Partial settlement leaves 30');
select throws_ok($$select public.record_item_settlement((select id from item),(select id from public.project_members where project_id=(select id from ctx) and role='member'),(select id from public.project_members where project_id=(select id from ctx) and role='organizer'),3001,current_date)$$,'P0001',null,'Cannot settle more than debt');
select throws_ok($$insert into public.payments(project_id,commitment_id,type,amount_minor,status,paid_on,paid_by_member_id,settlement_group_id) select ctx.id,item.id,'full',100,'paid',current_date,m.id,gen_random_uuid() from ctx,item,public.project_members m where m.project_id=ctx.id and m.role='organizer'$$,'P0001',null,'Unpaired settlement rejected');
update public.commitments set status='researching' where id=(select id from item);
update public.commitments set status='confirmed' where id=(select id from item);
update public.commitments set status='booked' where id=(select id from item);
select throws_ok($$update public.commitments set status='completed' where id=(select id from item)$$,'P0001',null,'Outstanding share still gates completion');
set constraints all deferred;
select lives_ok($$select public.record_item_settlement((select id from item),(select id from public.project_members where project_id=(select id from ctx) and role='member'),(select id from public.project_members where project_id=(select id from ctx) and role='organizer'),3000,current_date)$$,'Balance settlement supported');
set constraints all immediate;
select lives_ok($$update public.commitments set status='completed' where id=(select id from item)$$,'Fully settled booking completes');
select is((select net_actual_spend_minor from public.v_project_financials where project_id=(select id from ctx)),10000::bigint,'Partial and final settlement preserve expense');
create temporary table other_project as select public.create_project('Other','UTC','GBP',current_date,null,'blank') id;
create temporary table other_area as with a as(insert into public.project_areas(project_id,title) select id,'Other area' from other_project returning id) select id from a;
select throws_ok($$update public.commitments set area_id=(select id from other_area) where id=(select id from item)$$,'23503',null,'Cannot assign cross-project Area');
create temporary table recurring as select (public.save_activity_with_split((select id from ctx),null,jsonb_build_object('title','Repeat for Sarah','activity_type','task','owner_member_id',(select id from public.project_members where project_id=(select id from ctx) and user_id='31000000-0000-0000-0000-000000000003'),'recurrence_frequency','weekly','recurrence_interval',1,'recurrence_start_date',current_date),null)).id;
create temporary table viewer_cost as select (public.save_activity_with_split((select id from ctx),null,jsonb_build_object('title','Unpaid Sarah Item','activity_type','task','estimated_cost_minor',100,'owner_member_id',(select id from public.project_members where project_id=(select id from ctx) and user_id='31000000-0000-0000-0000-000000000003')),null)).id;
select pg_temp.login(3);
select throws_ok($$select public.complete_assigned_item((select id from viewer_cost))$$,'P0001',null,'Viewer completion respects financial gate');
select lives_ok($$select public.complete_assigned_item((select id from recurring),current_date)$$,'Viewer completes own recurring Item');
select throws_ok($$select public.complete_assigned_item((select id from recurring),current_date)$$,'P0001',null,'Cannot rewrite completed occurrence');
select throws_ok($$select public.complete_assigned_item((select id from recurring),current_date+1)$$,'P0001',null,'Cannot invent recurrence date');
select pg_temp.login(2);
select throws_ok($$select public.record_item_settlement((select id from item),null,null,1,current_date)$$,'42501',null,'Member cannot attribute another person settlement');
select lives_ok($$insert into public.project_areas(project_id,title) select id,'Member Area' from ctx$$,'Member creates Area');
select pg_temp.login(1);
set local role postgres;
update public.project_members set status='removed',removed_at=now() where project_id=(select id from ctx) and user_id='31000000-0000-0000-0000-000000000003';
select pg_temp.login(3);
select throws_ok($$select public.complete_assigned_item((select id from recurring),current_date+7)$$,'42501',null,'Removed Viewer denied');
select is((select count(*)::int from public.project_areas where project_id=(select id from ctx)),0,'Removed member cannot read Areas');
select pg_temp.login(1);

update public.projects set status='archived' where id=(select id from ctx);
select throws_ok($$insert into public.project_areas(project_id,title) select id,'Archived' from ctx$$,'P0001',null,'Archived Area write denied');
select * from finish();
rollback;
