/** Real develop E2E. BETA_FIXTURE_FILE contains synthetic accounts only, never printed. */
import fs from 'node:fs';import assert from 'node:assert/strict';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
import {chromium} from 'playwright';import {createClient} from '@supabase/supabase-js';
const target='msfkczsoutbeyhjvegnw',origin='http://127.0.0.1:4187';
assert.equal(fs.readFileSync('supabase/.temp/project-ref','utf8').trim(),target);
const fixturePath=process.env.BETA_FIXTURE_FILE;assert(fixturePath);const f=JSON.parse(fs.readFileSync(fixturePath,'utf8'));
const env=Object.fromEntries(fs.readFileSync('.env.local','utf8').split('\n').filter(l=>l.includes('=')&&!l.startsWith('#')).map(l=>{const i=l.indexOf('=');return [l.slice(0,i),l.slice(i+1).replace(/^['"]|['"]$/g,'')];}));
assert.equal(env.VITE_SUPABASE_URL,'https://'+target+'.supabase.co');
const backend=createClient(env.VITE_SUPABASE_URL,env.VITE_SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
assert.ifError((await backend.auth.signInWithPassword({email:f.users[0].email,password:f.users[0].password})).error);
const browser=await chromium.launch({headless:true,channel:'chrome'}),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ia-live-'));
let page;const violations=[];
async function login(user){const ctx=await browser.newContext();const p=await ctx.newPage();p.setDefaultTimeout(20000);await p.exposeBinding('cspViolation',(_,v)=>violations.push(v));await p.addInitScript(()=>document.addEventListener('securitypolicyviolation',e=>window.cspViolation(e.violatedDirective)));await p.goto(origin+'/login');await p.getByLabel('Email',{exact:true}).fill(user.email);await p.getByLabel(/^Password/).fill(user.password);await p.getByRole('button',{name:'Log in',exact:true}).click();await p.waitForURL(origin+'/app');return p;}
async function go(p,suffix){await p.waitForFunction(()=>document.querySelector('#app')?.__vue_app__);await p.evaluate(url=>document.querySelector('#app').__vue_app__.config.globalProperties.$router.push(url),'/app/projects/'+f.project+'/'+suffix);await p.waitForURL(origin+'/app/projects/'+f.project+'/'+suffix);}
async function rows(table){const r=await backend.from(table).select('*').eq('project_id',f.project);assert.ifError(r.error);return r.data;}
function checkpoint(key){f[key]=true;fs.writeFileSync(fixturePath,JSON.stringify(f),{mode:0o600});}
async function createItem(title,type,area,assignee,cost){
 if((await rows('v_project_items')).some(i=>i.title===title))return;
 await go(page,'areas');await page.getByRole('button',{name:'Add activity',exact:true}).click();const d=page.getByRole('dialog');
 await d.getByLabel('Activity title *',{exact:true}).fill(title);await d.getByLabel('Activity type',{exact:true}).selectOption(type);await d.getByLabel('Category',{exact:true}).selectOption({label:area});
 if(assignee)await d.getByLabel('Assigned to',{exact:true}).selectOption({label:assignee});
 await d.getByLabel(type==='task'?'Due date':'Date',{exact:true}).fill('2027-06-18');await d.getByLabel('Notes',{exact:true}).fill('E2E Activity notes');
 if(cost){await d.getByLabel(/^Cost \(/).fill(cost);await d.getByRole('button',{name:'Manage cost sharing'}).click();await d.getByLabel('Split cost',{exact:true}).selectOption('even');await d.getByRole('checkbox',{name:/Brendan/}).check();await d.getByRole('checkbox',{name:/Michael/}).check();}
 await d.getByRole('button',{name:'Create activity',exact:true}).click();await page.getByText('Activity created.',{exact:true}).waitFor();await d.waitFor({state:'hidden'});
}
try{
 page=await login(f.users[0]);
 if(!f.project){await page.evaluate(()=>document.querySelector('#app').__vue_app__.config.globalProperties.$router.push('/app/projects'));await page.getByRole('button',{name:'New project',exact:true}).first().click();await page.getByRole('button',{name:/Blank Project/}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByLabel('Project name').fill('Ibiza 2027');await page.getByLabel('Start date').fill('2027-06-12');await page.getByRole('button',{name:'Create project',exact:true}).click();await page.waitForURL('**/overview');f.project=page.url().match(/projects\/([a-f0-9-]+)\//)[1];checkpoint('created');}
 const sql=f.users.slice(1).map((u,i)=>`insert into public.project_members(project_id,user_id,display_name,email,role,status) values('${f.project}','${u.id}','${u.name}','${u.email}','${i===0?'member':'viewer'}','active') on conflict do nothing;`).join('\n');const file=path.join(tmp,'members.sql');fs.writeFileSync(file,sql,{mode:0o600});assert.equal(spawnSync('supabase',['db','query','--linked','--project-ref',target,'--file',file],{encoding:'utf8',timeout:60000}).status,0);
 await go(page,'areas');await page.reload();await page.getByRole('heading',{name:'Activities',exact:true}).waitFor();
 for(const title of ['Transport','Accommodation','Things to do']){if((await rows('project_areas')).some(a=>a.title===title))continue;await go(page,'areas');await page.getByRole('button',{name:'New category',exact:true}).click();const d=page.getByRole('dialog');assert.equal(await d.getByText(/Cost|Payment|Participants/).count(),0);await d.getByLabel('Category name').fill(title);await d.getByRole('button',{name:'Save category',exact:true}).click();await d.waitFor({state:'hidden'});await page.waitForURL('**/areas?area=*');}
 await createItem('Taxi from airport to Airbnb','booking','Transport','Brendan','100');
 await createItem('Michael to contact club','task','Things to do','Michael');
 await createItem('Sarah assigned item','task','Things to do','Sarah');
 let all=await rows('v_project_items');assert.equal(all.length,3);const taxi=all.find(i=>i.title==='Taxi from airport to Airbnb');
 if(!f.paid)assert.equal((await rows('v_project_financials'))[0].net_actual_spend_minor,0);
 if(!f.paid){await go(page,'areas?commitment='+taxi.id);const d=page.getByRole('dialog');await d.getByRole('button',{name:'Add payment',exact:true}).click();await d.getByLabel('Payment type').selectOption('full');assert.equal(await d.getByLabel('Amount',{exact:true}).inputValue(),'100');await d.getByLabel('Paid by',{exact:true}).selectOption({label:'Brendan'});await d.getByRole('button',{name:'Add payment',exact:true}).click();await page.getByText('Payment recorded.',{exact:true}).waitFor();checkpoint('paid');await d.getByRole('button',{name:'Close',exact:true}).click();}
 let finance=(await rows('v_project_financials'))[0];assert.equal(finance.net_actual_spend_minor,10000);
 const michael=(await rows('v_project_member_settlements')).find(m=>m.display_name==='Michael');
 if(!f.settled){assert.equal(michael.remaining_minor,5000);await go(page,'overview');const details=page.locator('details').filter({has:page.locator('summary').filter({hasText:'Michael'})});await details.locator('summary').click();await details.getByRole('heading',{name:'Transport',exact:true}).waitFor();await details.getByText('Taxi from airport to Airbnb',{exact:true}).waitFor();await details.getByRole('button',{name:'Mark settled',exact:true}).click();const d=page.getByRole('dialog');assert.equal(await d.getByLabel('Amount',{exact:true}).inputValue(),'50');await d.getByRole('button',{name:'Record settlement',exact:true}).click();await d.waitFor({state:'hidden'});checkpoint('settled');}
 assert.equal((await rows('v_project_member_settlements')).find(m=>m.display_name==='Michael').remaining_minor,0);assert.equal((await rows('v_project_financials'))[0].net_actual_spend_minor,10000);assert.equal((await rows('v_area_totals')).find(a=>a.area_id===taxi.area_id).spent_minor,10000);
 console.log('PASS live: Project → three Categories → three Activities; £100 expense, £50 debt, settlement leaves spend £100 and debt £0; no duplicate ledgers');
 await go(page,'overview');assert.equal(await page.getByRole('link',{name:'Settings',exact:true}).count(),0);await page.getByRole('button',{name:'Open project settings'}).click();let d=page.getByRole('dialog');await d.getByLabel('Timezone',{exact:true}).waitFor();await d.getByLabel('Currency',{exact:true}).waitFor();await d.getByRole('button',{name:'Close dialog',exact:true}).click();
 await go(page,'people');await page.getByText('Michael',{exact:true}).first().waitFor();await page.getByText('Sarah',{exact:true}).first().waitFor();
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export',exact:true}).click();const download=await downloadPromise;const csv=fs.readFileSync(await download.path(),'utf8');assert(csv.includes('"Transport","Taxi from airport to Airbnb","Booking"'));assert(!/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}/i.test(csv));assert.equal(csv.split('\r\n').filter(Boolean).length,4);
 console.log('PASS live: Settings dialog, People membership and real CSV download');
 const sarah=await login(f.users[2]);const assigned=all.find(i=>i.title==='Sarah assigned item');await go(sarah,'areas?commitment='+assigned.id);d=sarah.getByRole('dialog');if(!f.viewerDone){await d.getByRole('button',{name:'Complete',exact:true}).click();await d.getByText('Completed',{exact:true}).waitFor();checkpoint('viewerDone');}assert.equal(await d.getByRole('button',{name:'Edit',exact:true}).count(),0);await d.getByRole('button',{name:'Close',exact:true}).click();await go(sarah,'areas?commitment='+taxi.id);d=sarah.getByRole('dialog');assert.equal(await d.getByRole('button',{name:'Complete',exact:true}).count(),0);assert.equal(await d.getByRole('button',{name:'Add payment',exact:true}).count(),0);assert.equal(await sarah.getByRole('button',{name:'Open project settings'}).count(),0);
 console.log('PASS live: Sarah completes only her Activity; no title/cost/payment/settings edits');
 const member=await login(f.users[1]);await go(member,'areas');await member.getByRole('button',{name:'Add activity',exact:true}).waitFor();
 for(const width of [375,430,768,1280]){await page.setViewportSize({width,height:900});for(const suffix of ['overview','areas','budget','timeline','people']){await go(page,suffix);await page.getByRole('button',{name:'Export',exact:true}).waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow '+suffix+' '+width);}await page.getByRole('button',{name:'Open project settings'}).click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.getByRole('button',{name:'Close dialog',exact:true}).click();}
 await page.setViewportSize({width:375,height:900});await go(page,'overview');await page.screenshot({path:'/tmp/orchestrio-ia-375.png',fullPage:true});assert.deepEqual(violations,[]);checkpoint('passed');console.log('PASS live: 375/430/768/1280 layouts, Member permissions, CSP');
}catch(e){if(page)console.error((await page.textContent('body')).slice(-1600));throw e;}
finally{await backend.auth.signOut();await browser.close();fs.rmSync(tmp,{recursive:true,force:true});}
